export const productData = [
  {
    title: "Áo thun Polo 06",
    price: "194000",
    image01: "assets/productsImg/product_6.jpg",
    categorySlug: "ao-thun",
    colors: ["black"],
    slug: "ao-thun-polo-06",
    size: ["s", "m", "xl"],
    description: "",
  },
  {
    title: "Áo somi caro 07",
    price: "194000",
    image01: "assets/productsImg/product_7.jpg",
    categorySlug: "ao-somi",
    colors: ["white", "red", "orange", "blue"],
    slug: "ao-somi-caro-07",
    size: ["l", "xl"],
    description: "",
  },
  {
    title: "Áo somi dài tay 08",
    price: "194000",
    image01: "assets/productsImg/product_8.jpg",
    categorySlug: "ao-somi",
    colors: ["white", "red", "black"],
    slug: "ao-somi-dai-tay-08",
    size: ["s", "m", "xl"],
    description: "",
  },
  {
    title: "Áo somi tay dài 09",
    price: "194000",
    image01: "assets/productsImg/product_9.jpg",
    categorySlug: "ao-somi",
    colors: ["white", "blue"],
    slug: "ao-somi-tay-dai-09",
    size: ["m"],
    description: "",
  },
  {
    title: "Quần jean phong cách 10",
    price: "194000",
    image01: "assets/productsImg/product_10.jpg",
    categorySlug: "quan-jean",
    colors: ["blue", "black"],
    slug: "quan-jean-phong-cach-10",
    size: ["l"],
    description: "",
  },
  {
    title: "Quần jean 11",
    price: "194000",
    image01: "assets/productsImg/product_11.jpg",
    categorySlug: "quan-jean",
    colors: ["blue", "black"],
    slug: "quan-jean-11",
    size: ["s", "m", "xl"],
    description: "",
  },
];
